### ISSUE TITLE
Validate that offer's jobMaxDuration is greater than jobMinDuration

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#115]
This is a check that only occurs in the Model level (Offer Model), however, it should be added to the router layer as well (in the create validators and edit as well - as soon as #110 is done)

**Comment by BrunoRosendo** [comment]
If I'm not mistaken, the check in the edit validator is already done (in the jobMaxDurationEditable function in validators/offer). Thus, only the create validator is currently missing

**Comment by imnotteixeira** [comment]
Just checked, and that seems to be the case, yes.
