### ISSUE TITLE
Update edit offer route to verify for concurrent offers

### ISSUE THREAD

**Issue by DoStini** [NIAEFEUP/nijobs-be#121]
Apply concurrentOffers middleware to edit route

**Comment by DoStini** [comment]
Been looking at this, this needs to be applied to param `publishDate` and also `publishEndDate` if I'm not mistaken

**Comment by Naapperas** [comment]
I can handle this

**Comment by imnotteixeira** [comment]
Go for it! If you need any pointers, @DoStini might be a good bet, since he worked on the edit offer feature

**Comment by DoStini** [comment]
Absolutely, anything you need you can talk to me.

**Comment by imnotteixeira** [comment]
Also, don't bother creating the logic all over again, we already have a similar validator in place when creating offers, try to reuse it or extract common logic
