### ISSUE TITLE
Add company logo to offer details when returning it

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#128]
Currently, Offers have `owner` and `ownerName` fields identifying the company the offer belongs to.

In order to have the company logo on the frontend, it needs to request it for each offer/company, which will have bad performance due to the enormous amounts of requests it will require.

Instead, the returned Offer objects should include a field with the company logo path (URL if possible - depends on being stored locally or not - check #91)

In order to avoid having the same "many requests" problem, but this time on the backend, the best approach would be to tweak the mongoose queries that fetch the offers and include there the companies' logo URL, by using something like `.populate` (https://mongoosejs.com/docs/populate.html#field-selection). This way, there's only one query per offer search, optimizing the lookup.

**Comment by TiagooGomess** [comment]
I am going to assume that the name of the company logo parameter received in the offer GET request is `ownerLogo`.
