### ISSUE TITLE
Block Company from posting new offers

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#132]
Admins/god should be able to block a company from posting new Offers.

This block should be reversible by an admin/god only.

There should be a reason for internal consumption (stored in the company model?), so that we know why it was blocked --- it should be removed if the company is unblocked.

An email should be sent automatically when a company is blocked/unblocked

**Comment by DoStini** [comment]
After blocking a company, their current offers should be disabled as well? And when we unblock the company, those offers would be also enabled. If this is the case, we could use another hidden reason in offers like we're doing in #122. And then it would be easy to identify which offers were blocked by admins or by consequence of blocking the company.

**Comment by imnotteixeira** [comment]
Hmmm, that's a good question. In order to make it easier to implement + review, it might be better to separate this into two tasks, since I can see use cases for blocking companies from posting new offers only (avoiding spam, even though current offers are legitimate).

The other task would be to allow blocking future offers + current

**Comment by DoStini** [comment]
I'll create an issue after this PR then.
