### ISSUE TITLE
HTTPS development server

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#133]
After some issues in testing NIAEFEUP/nijobs-fe#80, I realized we would have a problem using Chrome to test frontend changes in Netlify (or using any kind of different backend for the frontend application).

The issue only affects chrome and basically boils down to it blocking cookies that have SameSite=Lax (which is the default) and which are passed to a different origin (in this case from netlify to our custom backend running locally - for me I was using ngrok, as per the nijobs-fe readme, but the problem would be the same no matter what tool I used, since the backend wouldn't be served through netlify, so the origin would be different)

The docs (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) state that in order for cookies to be passed between different origins, they need to have SameSite=None. That's an easy fix: one just needs to add it to the cookie options in the session middleware. However, SameSite=None, only works with **secure** cookies. This is where things get interesting...

In order to use secure cookies, we need to use HTTPS. For the frontend, our setup already allows it, by simply providing HTTPS=true as an env var. By using ngrok, and setting the API hostname to the HTTPS version, we would have an HTTPS frontend calling a different (different origin) HTTPS backend, and since we have SameSite=None and Secure=true, everything works.
(For this to really work correctly, the `proxy` option must also be set to true in the session middleware - as it is being done in production only, currently)

But this raises the problem: what about normal development in localhost? It should still work after whatever fix we apply...
Well, if we do the above, when using the normal localhost:8087 server (without ngrok), things won't work since the HTTPS frontend will be calling an HTTP backend, which is not allowed.

This leads me to the main point: we should make the dev version of the Backend serve an HTTPS API, which would allow local development, by using HTTPS on both ends, and also making it possible to communicate with Netlify (or other different host with a frontend) via HTTPS and have no Cookie problem.

In order to achieve this, I found this Post (https://medium.com/@nitinpatel_20236/how-to-create-an-https-server-on-localhost-using-express-366435d61f28) which explains how to do it, and I think we can add the necessary config to a script and even make it part of the Docker-dev setup, to make it easier. It uses a self-signed certificate, so the work should be minimal.

The only missing piece is to find out if the `proxy` option being true when there is no proxy (localhost only) will cause any problem. I don't believe it will, but if it does, we'll have to create an env option for devs to toggle it when using localhost or ngrok (or another proxy)

**Comment by miguelpduarte** [comment]
I would almost consider just using something like [Caddy](https://caddyserver.com/) to proxy the requests, but that seems more of a pain to be able to run locally without docker, so I guess the current approach with self-signed certificates is the easiest option atm.
