### ISSUE TITLE
Allow Companies to disable their account

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#139]
Companies should be able to disable their account, making them invisible to the users.

Their offers should also be hidden (not deleted!)

This should be a temporary state, allowing companies to re-enable them

A God (not admin) should be able to do it as well

**Comment by imnotteixeira** [comment]
Such as with #148, there should be a new offers' hidden reason for this scenario. Something like `COMPANY_DISABLED`

**Comment by Naapperas** [comment]
Maybe I could work on top of #148 's feature of enabling/disabling offers when some information about a company changes.

**Comment by imnotteixeira** [comment]
> 
> 
> Maybe I could work on top of #148 's feature of enabling/disabling offers when some information about a company changes.

Hmmm, I think offers should only be affected when the company changes drastically (i.e., a name change, or the company is disabled/deleted), they should not be affected on a bio/contacts change for example
