### ISSUE TITLE
Allow Companies to delete their account

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#140]
Allow a company to delete their account, and related offers.

A God (not admin) should be able to do it as well

**Comment by DoStini** [comment]
I'm thinking since this is such a disruptive action, this should be confirmed via email.

**Comment by imnotteixeira** [comment]
I agree, but I feel like we can do that feature after MVP. Let's have the option to delete companies and trigger the deletion of their offers first, and then have another issue to track that functionality.

---

Regarding the feature:

My suggestion is to have an endpoint that generates a code (valid for a limited period, that is required in order to call the delete endpoint)

Then, we could call that endpoint to generate it and send the email. On the frontend, we would do that before calling the "delete" endpoint and ask the user to check the email and give us the code, with which we would call the delete endpoint.

This is probably the easiest option, while having a good UX, another option I thought about was to generate a deletion token when calling the delete endpoint, and then we would send an email for users to go to /api/delete/confirm/:token, but it wouldn't have a nice UI since that would still be an API call, and to have a UI to match that page is probably more work than the first solution, but we can discuss it here.

**Comment by Naapperas** [comment]
>  and trigger the deletion of their offers first

Wouldn't this functionality contradict the purpose of #100 ?

**Comment by imnotteixeira** [comment]
> 
> 
> > and trigger the deletion of their offers first
> 
> Wouldn't this functionality contradict the purpose of #100 ?

Yes, nice catch. This is something we need to discuss. I don't know to what extent RGPD applies here so I don't know if we can do #100 or must delete it as proposed here.
