### ISSUE TITLE
Creating offer with company not working

### ISSUE THREAD

**Issue by DoStini** [NIAEFEUP/nijobs-be#144]
After #138, companies cannot create offers since the middleware used only accounts for admin accounts.
https://github.com/NIAEFEUP/nijobs-be/blob/baef2d94f0beed9b59ba0d0e98eb5540f6055085/src/api/middleware/company.js#L38
In principle just replace `req.body.owner` with `req.user.company || req.body.owner` and add a test to verify this situation.

**Comment by imnotteixeira** [comment]
Actually, it should be `req.user?.company || req.body.owner` since if it is being created in god mode, there might not be a user even.

**Comment by imnotteixeira** [comment]
After giving this a better look, and to avoid this being a problem in the future again, I think we should have a middleware that instantiates a `req.ownerCompany` which will be `req.user?.company || req.body.owner`. Then, the inner functions just need to use this value, and avoid duplicating this logic.

**Comment by joaomrcsmartins** [comment]
Add parameter to request in `routes/auth` and refactor in the whole project

**Comment by imnotteixeira** [comment]
Here's a hidden one

https://github.com/NIAEFEUP/nijobs-be/blob/1b277c87e024329ea5173b7b0e9fb9fd67fcb12a/src/services/offer.js#L231

When an offer is hidden, a god would not be able to access it by id in this case
