### ISSUE TITLE
Trigger offer hiding when companies are blocked

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#148]
Once a company is blocked (after #143 goes through), there should be a mongoose hook that runs and hides all the offers from that company.

To make it clearer, there should be another HiddenOfferReason such as `COMPANY_BLOCKED` in https://github.com/NIAEFEUP/nijobs-be/blob/develop/src/models/constants/Offer.js and use that value in this scenario.

By doing this, we can revert it if the company gets unblocked, by "un-hiding" the respective offers

**Comment by DoStini** [comment]
So is this supposed to be a new route, or should it always be executed on a company block?

**Comment by imnotteixeira** [comment]
It should always happen. No extra route

**Comment by imnotteixeira** [comment]
In order to prepare for the future feature of "blocking only future action (and leaving current offers as is)", instead of using a mongoose hook, you might need to do it "manually" by calling some service function after the .block call, which does different things based on the intention of the block
