### ISSUE TITLE
Add sample .env file

### ISSUE THREAD

**Issue by xRuiAlves** [NIAEFEUP/nijobs-be#17]
I think it might be insteresting to add a semple env file in the repo's root (e.g. `.env.example`) instead of explaining how to setup the env file in the README.

We could even add a `.env` file and setup [dotenv-flow](https://www.npmjs.com/package/dotenv-flow) to allow overriding the env file with a local version (e.g. `.env.local`).
This change would allow the README setup instructions to become simpler aswell: just run `cp .env .env.local` and fill in the variables.

If this is done, we should also add a `.env*.local` entry to the `.gitignore`.

**Comment by miguelpduarte** [comment]
As replied in the FE issue, this sounds pretty good to me, even reducing the documentation strain in the README (would be able to just refer to the .env file and maintain it as the single source of truth).

I'm for it, and dotenv-flow is a good idea, I have had good experience with it 😄
