### ISSUE TITLE
[Bug] Remove email normalization on company applications

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#172]
Currently, emails get normalized before being stored in the company applications, which may cause changes to them, as can be seen in the validator.js docs https://github.com/validatorjs/validator.js/#sanitizers (check the `normalizeEmail` sanitizer)

This has many problems: the first is that, for example, if someone uses a "john.doe@gmail.com" email, it would be normalized and changed to "johndoe@gmail.com" (without the '.'), and the company wouldn't be able to login with the initial one. Similar things happen if they use @googlemail.com instead of @gmail.com.

In my case, I was trying to use the "+" trick, where I use the same email, but add a `+<suffix>`  to be able to differentiate sources, will still using the same email (e.g. myemail+nijobs@gmail.com would still redirect mail to myemail@gmail.com, but I can filter based on the +nijobs suffix)

This does not work, due to the normalizeEmail call, which made me think about if we need it at all. And my opinion is that we don't as it causes more harm than good, so we should remove it.

https://github.com/NIAEFEUP/nijobs-be/blob/6fbaf4d0703528e70f5b46e170337925ff8316a8/src/api/middleware/validators/application.js#L18

**Comment by BrunoRosendo** [comment]
I agree that we should just use the raw e-mail companies provide, even if they use the "+" trick. I'll open a patch :)
