### ISSUE TITLE
[Bug] Email sending fails when NI's website is down

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#174]
We currently use the NIAEFEUP logo on our emails by fetching the resource at `https://ni.fe.up.pt/images/logo-niaefeup.png`. However, that fails if the website is down, resulting in the error below. This results in an error on company application submission, for example.

We should find an alternative to hosting the logo somewhere else, in order to kill the dependency on the NIAEFEUP's website.

![image](https://user-images.githubusercontent.com/28157246/129450008-d75bee8c-f586-4b81-977f-27d2064193d7.png)

**Comment by DoStini** [comment]
Could we store it in the server where our containers will be running? Or should we use some sort of external image hosting website?
We should also fix this bug so that the email is sent even if the logo is missing.

**Comment by Naapperas** [comment]
Maybe we could have the image hosted both externally and on NIAEFEUP's website, because we have no guarantee that the external service will never fail, and start by attempting to fetch the image first locally (I imagine it would be faster) and, if that fails, use the external service as a backup. What do you think ?

**Comment by imnotteixeira** [comment]
> 
> 
> Maybe we could have the image hosted both externally and on NIAEFEUP's website, because we have no guarantee that the external service will never fail, and start by attempting to fetch the image first locally (I imagine it would be faster) and, if that fails, use the external service as a backup. What do you think ?

This would work, but it's an overcomplicated solution to a simple problem: the emails fail to be sent when the logo is missing. NIJobs should simply host the image itself and the problem is solved. Better yet, I think it fails because we are sending the image as an attachment. If we just send the email HTML with an `<img src="nijobs URL for logo" />` even if the logo is missing, the email would be sent regardless I think, and it would simply cause an image rendering failure on the receiver.

**Comment by imnotteixeira** [comment]
Confirmed. The attachment is added here:

https://github.com/NIAEFEUP/nijobs-be/blob/6ad5ea03cfe2a2c6fdf1f487ed48c22c7ac04581/src/lib/emailService.js#L63L67

And used in the template by referencing the attachment, instead of an external URL here:

https://github.com/NIAEFEUP/nijobs-be/blob/6ad5ea03cfe2a2c6fdf1f487ed48c22c7ac04581/src/email-templates/layouts/main.handlebars#L9

**Comment by DoStini** [comment]
Using directly 
`<img style="margin-right:20px;" src='https://nia.fe.up.pt/images/logo-niaefeup.png' alt='logo niaefeup' title='logo' style='display:block' width='94'>` 
it loads the image correctly when the logo exists and it leaves the alt when the logo is not available.


![image](https://user-images.githubusercontent.com/23351316/131478878-8cee7c17-d09b-4da3-b941-64c11e6e0351.png)
