### ISSUE TITLE
It's possible for a company to create an infinite number of offers

### ISSUE THREAD

**Issue by TiagooGomess** [NIAEFEUP/nijobs-be#186]
When I tried to create some offers for a specific company, I realized that when the number of created offers surpasses 5, there is no error, even if all of the offers are visible.

**Comment by DoStini** [comment]
JS Moment, `req.body?.isHidden` is being parsed as a string instead of a boolean, so it parses as true in https://github.com/NIAEFEUP/nijobs-be/blob/161938ca57765115847f2f80f5d5421fefa7f183/src/api/middleware/company.js#L30

**Comment by Naapperas** [comment]
This happened when testing manually because we were sending this field as `"true"`, I just checked and we are sending a boolean in the E2E tests. Maybe we can check if it is a string and if it is parse it to a boolean, else if it is a boolean to begin with just keep that value ?

**Comment by TiagooGomess** [comment]
Maybe you can use `JSON.parse(offer.?isHidden)`:

![Screenshot from 2021-09-16 12-27-33](https://user-images.githubusercontent.com/50210213/133604306-38fb6e2f-00db-4350-984b-8d994ddce93a.png)

This way you don't need to check if it's string or boolean.
