### ISSUE TITLE
Improve code structure

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-be#19]
`Express` is a decent library/framework (who cares, really?), but it does not enforce any structure at all, which can result in getting stuff all over the place.

So, we should follow something like [this](https://softwareontheroad.com/ideal-nodejs-project-structure/) - I'm reading it now and it all makes a lot of sense. We can iterate on it, but I feel that at least a basic level of what's described there should be implemented :smile:

**Comment by miguelpduarte** [comment]
Would like to have some insight/discussion on this, to get some opinions before enforcing too much stuff

**Comment by imnotteixeira** [comment]
Didn't have the chance to dive deep into that solution, but I liked the general ideas in there, which promote code reliability and improve structure, making this project maintainable, which should be one of the goals. That being said, I approve.

**Comment by xRuiAlves** [comment]
+1

**Comment by miguelpduarte** [comment]
Cool beans, will bother you both when the PR eventually drops 😄 

(Probably should finish up #7 first, long time coming and almost done - it's on `feature/database`, should open a draft PR today and finish up soonTM - will need to fix my old code surely 🙃 )
