### ISSUE TITLE
Location Service Endpoint

### ISSUE THREAD

**Issue by DoStini** [NIAEFEUP/nijobs-be#199]
Currently, we are using Geodb Cities API, which is very incomplete. For example, Aveiro is not available.

We should implement our own endpoint to search for possible locations

**Comment by DoStini** [comment]
I have left a csv file with over 40k entries in slack which we could use. 

I'm thinking we could migrate it to our database

**Comment by imnotteixeira** [comment]
MongoDB Atlas free tier is limited to 512MB so this is fine (the file has around 4MB, even if this takes up to 10MB in the DB, it should be ok)

Remember that we need to process the info from the csv in a way that is easily searcheable (the main goal of this service) so we need to index these ready for free text search. It might be useful to have a script that takes the csv file and creates the records on the mongodb. It would also be nice to have a way of adding an entry and index it if we need to do it later.

**Comment by Naapperas** [comment]
Under which route should this endpoint be served ?

**Comment by imnotteixeira** [comment]
> Under which route should this endpoint be served ?

`/location/search`

**Comment by Naapperas** [comment]
For further information on this feature go to [NIJobs Locations](https://github.com/NIAEFEUP/nijobs-locations)
