### ISSUE TITLE
Update constants

### ISSUE THREAD

**Issue by DoStini** [NIAEFEUP/nijobs-be#218]
- This PR contains a lot of values for fields and technologies but they should be revised and updated 
    -  #71 
- Should we update the value of max concurrent offers, regarding the feedback of companies and to maximize the quantity of offers to students
- Revise other constants such as number of maximum contacts

**Comment by BrunoRosendo** [comment]
Do the changes in that PR make any sense for today's NIJobs? I think I should just take the enums from there but I wanted to confirm
