### ISSUE TITLE
Re-structure Docker configuration

### ISSUE THREAD

**Issue by xRuiAlves** [NIAEFEUP/nijobs-be#24]
- All dev and test dockerfiles should not exist. For development purposes, devs should install npm (using a versioning tool like `nvm` or `asdf`). This information should be added to README as versioning tools suggestions.
- Production dockerfiles should be consistent with niaefeup/niployments#1

**Comment by xRuiAlves** [comment]
niaefeup/niployments

**Comment by imnotteixeira** [comment]
Closing as this is actually helpful, as it allows devs to emulate the prod environment exactly locally, as well as running the tests as they will run on the CI, which can vary if depending on user's system
