### ISSUE TITLE
Uniformize services to either return a Promise or a Query

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/nijobs-be#246]
Currently, some of the services return a Promise while others return a Query. We should make this consistent across all the services. It probably makes more sense to return a Promise in all of them, to make sure we don't depend on the service's implementation.

Here are some examples:
[Service returning a Promise](https://github.com/NIAEFEUP/nijobs-be/blob/73c899fd61b0e0a6dd512e5be134106554573f0c/src/services/offer.js#L22), notice the use of async/await
[Service returning a Query](https://github.com/NIAEFEUP/nijobs-be/blob/73c899fd61b0e0a6dd512e5be134106554573f0c/src/services/company.js#L68), notice that it just returns the query

**Comment by Naapperas** [comment]
This was not an issue since Mongoose queries are `thenable` (see [this](https://masteringjs.io/tutorials/fundamentals/thenable) link) and are "awaited" in the route. Nonetheless, we should not mix things up.
