### ISSUE TITLE
Any user can see a hidden offer

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/nijobs-be#250]
Currently, we're setting a `req.targetOwner` in each request related to offers or companies. We do it this way, as can be seen [here](https://github.com/NIAEFEUP/nijobs-be/blob/6da1c15376767e493f9fe38358c8fbe436993de6/src/api/middleware/offer.js#L21):
- If the user is logged in as a company, use their id
- Otherwise, check if the request has the `owner` parameter and use that

The problem is that we set the `targetOwner` even if the user is not logged in and doesn't have any special permissions (admin or god). Because of this, if we try to access a hidden offer in the `offer/:offerId` endpoint, a regular user can see it as long as they know the company's ID (which is easy to discover with the company endpoints), like this:
```
GET /offers/:offerId

{
  "owner": ":ownerId"
}
```

I see two ways we can fix this:
- Change the `setTargetOwner` to only use the `owner` parameter when the user has admin privileges (including god). We need to make sure this doesn't break other functionalities using this function. I still think this is the preferred way.
- Instead of passing `targetOwner` to the offer service, we could pass `req.user?.company?._id`, to make sure we only allow the user if they have admin privileges or if they're logged in as the owner. However, I don't really like this approach because we should use `targetOwner` whenever possible, it should have the same permissions across the whole website

**Comment by BrunoRosendo** [comment]
Actually, I said I didn't like it but it might make sense to not use the `owner` parameter in this endpoint. The admins can already see hidden offers, so there isn't really any point in having it here.

Still, we should think if the `targetOwner` should be changed like I suggested. If so, the problem is fixed. Otherwise, we leave the `targetOwner` as is and stop using it in this endpoint

**Comment by BrunoRosendo** [comment]
This probably also happens in `/offers/company/:companyId` so please check other endpoints

**Comment by limwa** [comment]
I have opted to go with your first option as it does seem like it's the easiest to implement and the one that has the least potential to break things.

Either way, later today, I'll be testing to check if any functionality has been broken.

**Comment by limwa** [comment]
So, after testing for a bit, I've come across a problem. I am currently setting the targetOwner to the owner property if and only if the user has admin privileges.

This works for hiding the offers, but I'd like to hear your opinions regarding the error messages given. For instance, when using the owner property, if the user doesn't have access to the offer, an error message appears saying that there is no offer with that id. Should we keep this behavior to prevent unwanted enumeration of the offers or do we display an error like "insufficient-permissions"?

@BrunoRosendo
