### ISSUE TITLE
`sendPasswordRecoveryNotification` not asynchronous

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/nijobs-be#268]
Currently, this function is not declared as `async` and doesn't `await` the email service:
https://github.com/NIAEFEUP/nijobs-be/blob/c272e3bbbda9937b4ec7c2c4d8ac6bbb811684c7/src/services/account.js#L58

This is probably not intended and should be fixed. However, the route should **not** wait for this operation to complete, since we always send an OK response even if the email failed (e.g. it doesn't exist and we don't want to leak information)

**Comment by DoStini** [comment]
I think this is intended. Back when I was doing this issue, we discussed that for security reasons the response of the recovery should be always OK. So maybe we don't need to wait for the email to be sent (actually, waiting for the email to be sent causes the request to take longer than a request that doesn't find an email. This will indicate that an account was found)

**Comment by BrunoRosendo** [comment]
@DoStini You're right, it's intended, I didn't remember that when I opened the issue. However, shouldn't the service still by async and only the route not use await?
