### ISSUE TITLE
Implement DB Indexes

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-be#27]
See https://github.com/NIAEFEUP/nijobs-be/pull/20#discussion_r314994151

**TL;DR:** Should we have indexes in the DB? I'm feeling that this _should_ be a yes, but the complex searching by several fields makes this not very clear.

**Comment by imnotteixeira** [comment]
As we are not expecting a lot of data, mainly in the MVP, I would consider this an improvement only for a further future. 

The only relevant index I would see, for now, would be a Full-Text Search index, but I am not sure if that functionality is completely available as of now (https://docs.atlas.mongodb.com/full-text-search/?jmp=docs#full-text-search)

**Comment by miguelpduarte** [comment]
@imnotteixeira Agreed.

Furthermore, it seems that this would only be available in Atlas. We are using it for deployments, but I'm not sure how this would impact development. Additionally, I'm not sure of mongoose's support for it.

**Comment by imnotteixeira** [comment]
This might a be useful read: https://stackoverflow.com/questions/28775051/best-way-to-perform-a-full-text-search-in-mongodb-and-mongoose (together with the docs - https://docs.mongodb.com/manual/core/index-text/)

**Comment by imnotteixeira** [comment]
This has been done in #55 (#99). Closing
