### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by nip10** [NIAEFEUP/nijobs-be#32]
In the /register route, if the user is not succesfully created, the response will be:

https://github.com/NIAEFEUP/nijobs-be/blob/86739e1b051beffbdc70418f44ef0e35d678a9ca/src/routes/auth.js#L68-L72

The specified reason is not always true since the error can be caused by other reasons: bcrypt fails to generate salt or hash the pw, db connection issues, etc.
Its also important to distinguish a bad request (400) from server errors (500).

A possible solution is to use error types or codes. For example, Mongo provices an error code for duplicate entries (11000), so something like this can work:

```js
if (error.code === 11000) {
      return res.status(400).json({
            "success": false,
            "reason": "Duplicated username",
            "error_code": ERROR_TYPES.DB_ERROR,
        });
    }
    return res.sendStatus(500);
```

I'd also suggest to drop the JSON notation on res.json since it accepts JS objects and makes the code more readable.

**Comment by imnotteixeira** [comment]
I believe this has been updated in such a way that it is no longer relevant. However, we should log the error to the console before calling `next()` here, as is being done in other places throughout the application:
https://github.com/NIAEFEUP/nijobs-be/blob/9c918ca46fb46e72a564b9b6347eb91843b8458b/src/api/routes/auth.js#L60
