### ISSUE TITLE
Narrow CORS origin allowance

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#41]
When setting up CORS headers, all origins are being allowed to call this API, which is not ideal in a production environment. (`src/loaders/express.js`)

Instead, the `Access-Control-Allow-Origin` header should read the value from an env file, so that we could have only our trusted sources call our API, such as the application Frontend (http://github.com/NIAEFEUP/nijobs-fe/).

Surely, in the development env file, the allowed origins can still be `*` for an easier development

**Comment by miguelpduarte** [comment]
Discussion that resulted in creating this issue for reference: https://github.com/NIAEFEUP/nijobs-be/pull/38#discussion_r329362834
