### ISSUE TITLE
Edit Offers

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-be#59]
A Company Account should be able to edit its Company's Offers.

**Comment by DoStini** [comment]
Maybe use some middleware validation similar to the new offer to verify some fields:
- JobMinDuration less than jobMaxDuration
- publishEndDate not in the future

Some field shouldn't be changed:
- Owner
- OnwerName

**Comment by imnotteixeira** [comment]
I've been thinking about this, and I'm not sure we want to allow too much editing. In that case companies could change an offer completely and it would result in bad UX for people looking for offers (e.g. they bookmark a specific offer and when they go back it's completely different)

So, what if we only allow the Offer owners to change the description? (Even the title I think is too important to be editable by companies)

However, I believe that admins could still be able to edit respecting the rules @DoStini mentioned above

**Comment by imnotteixeira** [comment]
cc @miguelpduarte and @andrefmrocha if you want to chip in, since this involves some kind of "product tenets" discussion

**Comment by andrefmrocha** [comment]
Can you think of any use cases where the rest of the company's account should not be able to edit it? How do websites like LinkedIn handle this, does anyone know? 
Pinging @GambuzX to also have a say on this.

**Comment by imnotteixeira** [comment]
I don't think I understood the question
>  In that case companies could change an offer completely and it would result in bad UX for people looking for offers (e.g. they bookmark a specific offer and when they go back it's completely different)

**Comment by DoStini** [comment]
> I've been thinking about this, and I'm not sure we want to allow too much editing. In that case companies could change an offer completely and it would result in bad UX for people looking for offers (e.g. they bookmark a specific offer and when they go back it's completely different)

Regarding this issue, maybe we would only allow editing if the offer is not pusblished yet (I don't know if publishDate is actually allowing scheduled offers). And also maybe a time interval for the company to correct some typos would be useful aswell.

**Comment by imnotteixeira** [comment]
That's a good idea!
Still, no owner/ownerName changing (ownerName changing is only possible if the company itself changes its name, but that's already done automatically)

Changing is allowed if the offer is not published **yet**, since we want to keep a record of past offers as well, so only editable if `Date.now < publishDate`

Regarding a grace period for editing, I'd say **1h**, but it is not possible to implement now since we don't have `createdAt`. If you want to do it, you'll have to add this field, which defaults to `Date.now` and is required, and also while you're at it you could have and `updatedAt`, also required and default to now, but have a mongoose update hook that updates it on every update to the current time

**Comment by DoStini** [comment]
If we allow editing while the offer is not yet published, I think we would just need to verify the grace period with publishDate

**Comment by imnotteixeira** [comment]
Yes, but imagine the company publishes right away, you'd still want to have a grace period. Also, if publishDate is in the future (scheduling) by checking the publishDate you're giving an additional time for editing.

My idea is:
* If publishDate in the future -> allow editing
* else if publishDate in the past, but not more than EDIT_GRACE_PERIOD (1h) ago -> allow editing
* else -> prevent editing

**Comment by DoStini** [comment]
Exactly, I think that in this specific case adding `createdAt` wouldn't be necessary, because if the company publishes right away `publishDate` will be set to `date.now`, right?

**Comment by imnotteixeira** [comment]
The problem is not the "now" publishing. It's the future. If you have a grace period for"now+1hr" by comparing with publishDate, you'll be allowing companies to edit scheduled offers after they are published
