### ISSUE TITLE
Register, Login and Apply endpoints for companies

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-be#6]
Endpoints to add:
* Register
* Login
* Apply for our site

The login endpoint should receive the following fields:
* Email
* Password

The register endpoint should receive the following fields (the one time token is not yet in use):
* Email
* Nome da empresa
* Password

The apply for our site endpoint should receive the following fields:
* Email
* Nome da empresa
* Motivação
* Outros contactos

**Comment by miguelpduarte** [comment]
Should also probably split these issues, especially since register without token and login are already done

**Comment by imnotteixeira** [comment]
Closing as #91 is complete
