### ISSUE TITLE
Update nodejs versions in Dockerfiles

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-be#65]
The node versions we are using in the Dockerfiles seem to be LTS 8. However, the current LTS is 12.14.1.

We should update the app to this LTS, alongside the dockerfiles and any other configurations that need changing.

This is quite pressing as the version mismatch is pretty high.

**Comment by imnotteixeira** [comment]
Could we do this as part of the migration to CircleCI?

**Comment by miguelpduarte** [comment]
@imnotteixeira sure, but this would have priority over that since it also impacts production deployments. If circleci setup is being a blocker this should be pushed nonetheless.
