### ISSUE TITLE
Implement base MongoDB Schema

### ISSUE THREAD

**Issue by FilipePintoReis** [NIAEFEUP/nijobs-be#7]

**Comment by miguelpduarte** [comment]
Edited the title in order to split the work, in order to reduce the bottlenecks.

**Comment by miguelpduarte** [comment]
The main focus would then be the Company and Ad Schemas.

Logging and Reports should be pushed down in the priority list, I will create a separate issue for each of them.

**Comment by miguelpduarte** [comment]
Note: Implement(ing) based on the pre discussed Schema, with the relevant adaptations for MongoDB (Ad might end up being a big collection, and some other "tables" might be "sucked into" it)
