### ISSUE TITLE
GET Offer info and POST new Offer endpoints

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-be#8]
Relevant information:
* Tags
* Localização
* Tipo de emprego
* Título
* Descrição
* Data de início e duração (podem ser indefinidas)
* Vagas
* Checkbox de ser remunerado ou não (mostrar no site mas não ter como critério de filtragem)
* Requisitos (formato form do Postman)

**Comment by miguelpduarte** [comment]
Endpoint de informação reduzida, para os cards:
* Title
* Company
* Company Logo
* Job type
* Location
* Published at
* Tags
* First 3 requirements

**Comment by imnotteixeira** [comment]
Will close this issue, as it is too big.

To track this, I've created two other issues: #95 and #96
