### ISSUE TITLE
Add tests for Company User /auth/me information

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#86]
Currently, the `/auth/me` endpoint is only tested with an admin account.

Create another test where a company representative account is used and the correct information is retrieved. Also, test the case if for some reason the company linked to it does not exist (it should not return, but the request should succeed with the rest of the information)

**Comment by Process-ing** [comment]
The test for a normal company representative account was already made. See `test/end-to-end/auth.js line 178`.
`
       test("should return the informations of the logged in user (company)", async () => {
            await test_agent
                .post("/auth/login")
                .send(test_user_company);

            const res = await test_agent
                .get("/auth/me")
                .send();

            expect(res.status).toBe(HTTPStatus.OK);
            expect(res.body).toHaveProperty("data.email", test_user_company.email);
            expect(res.body).toHaveProperty("data.isAdmin", false);
            expect(res.body).toHaveProperty("data.company", expect.objectContaining(
                JSON.parse(JSON.stringify(test_company.toObject())) // Necessary since mongoose objects don't play well with jest...
            ));
        });`

**Comment by Naapperas** [comment]
This needs to be further reviewd to see if there is actual work to be done.

**Comment by Process-ing** [comment]
A company representative account without a linked company cannot be created. The code in `src/models/Account.js lines 17-22 and 30-36` ensures this.
