### ISSUE TITLE
Add structured requirements to offers

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#95]
In order to have a common and easy way of listing requirements on offers, we should have a `requirements` field that is separated from the description, and lists the requirements.

To simplify, it can be a simple String array, where each entry is a requirement.

Later on, we can have smarter requirements, as a Map with specific keys, to be able to have experience restrictions, knowledge in specific areas, etc...

**Comment by BrunoRosendo** [comment]
I linked a PR which tries to implement the array version of the requirements field. I assumed the field was mandatory (required) but I'd appreciate confirmation on this
