### ISSUE TITLE
Get offer info

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#96]
Create an endpoint to return the information about a specific Offer.

Something like GET /offers/:offer-id will do.

It should return:
* location
* jobType
* title
* description
* jobStartDate (might be undefined)
* minDuration and maxDuration
* vacancies
* isPaid
* requirements (if implemented after #95 )

**Comment by DoStini** [comment]
Unused optional values should be returned as `vacancies : undefined` or not show up in the response?
